routes/web.php
<?php

/*Route::get('text',function(){
$user = new App\User;
$user->name = 'david';
$user->email = 'david@gmail.com';
$user->rol = 'docente';
$user->password = bcrypt('12345678');
$user->save();

return $user;
});*/

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*Controller personalizazados */
Route::get('/',['as' => '/', 'uses' => 'HomeController@index'])->middleware('auth');


Route::resource('persona', 'PersonaController');

Route::resource('matricula', 'MatriculaController');

Route::resource('users', 'UserController');

Route::resource('aula', 'AulaController');

Route::resource('grupo', 'GrupoController');

Route::resource('programacion','ProgramacionController');

Route::resource('contenido','ContenidoController');

Route::resource('perfil', 'PerfilController');

Route::get('pdf/reporte', 'pdfcontroller@reportepdf')->name('reporte.pdf');
Route::get('pdf/reportemes', 'pdfcontroller@reportemesanterior')->name('reportemes.pdf');
Route::get('pdf/reporteactual', 'pdfcontroller@reportemesactual')->name('reporteactual.pdf');
Route::get('view/reporte', 'pdfcontroller@viewpdf')->name('vista.pdf');
Route::get('view/acercade', 'pdfcontroller@acercade')->name('vista.acercade');
Route::get('view/mapa', 'pdfcontroller@mapanavegacion')->name('vista.mapanav');
Route::get('view/ayuda', 'pdfcontroller@ayuda')->name('vista.ayuda');




Route::post('persona/activar', 'PersonaController@activar')->name('persona.activar');
Route::post('users/activar', 'UserController@activar')->name('users.activar');
Route::post('aula/activar', 'AulaController@activar')->name('aula.activar');
Route::post('grupo/activar', 'GrupoController@activar')->name('grupo.activar');
Route::post('matricula/activar', 'MatriculaController@activar')->name('matricula.activar');
Route::post('programacion/activar', 'ProgramacionController@activar')->name('programacion.activar');
Route::post('contenido/activar', 'ContenidoController@activar')->name('contenido.activar');


/*End personalizazados */

/*Login y passwor reset */

Route::get('login', 'Auth\LoginController@showLoginForm');

Route::post('login', 'Auth\LoginController@login');

Route::get('logout', 'Auth\LoginController@logout');

Route::get('password/reset','Auth\ForgotPasswordController@showLinkRequestForm');

Route::post('password/email','Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');

Route::get('password/reset/{token}','ResetPasswordController@showResetForm')->name('password.reset');

Route::post('/password/reset','ResetPasswordController@reset')->name('password.send');

Auth::routes();
/*Fin login y Pssword reset */

Route::resource('home','HomeController');

app/Http/Controllers/ProgramacionController.php
<?php

namespace App\Http\Controllers;

use DB;
use Illuminate\Http\Request;
use App\Http\Requests\ProgramacionRequest;
use App\Model\Programacione;
use App\Model\Contenido;
use App\Model\Persona;
use App\Model\Grupo;
use Carbon\Carbon;
use Notify;
use Datatables;

class ProgramacionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $persona = Persona::all()->where('Id_tipopersona','=','1');
       $contenido = Contenido::all()->where('estado','=','1');
       $grupo = Grupo::all()->where('estado','=','1');
       $programacion = Programacione::all()->where('estado','=','1');
       $estado = Programacione::all()->where('estado','=','0');
       return view('programacion.horario',compact('programacion','estado','contenido','persona','grupo'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProgramacionRequest $request)
    {
        $input = $request->all();
        Programacione::create($input);
        Notify::success("Registro exitoso");
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $programacion = Programacione::findOrFail($request->idprogramacion)->update($request->all());
        Notify::success("actualizados","Datos");
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        DB::table('programaciones')->where('idprogramacion',$request->idprogramacion)->update(['estado' => 0]);
        Notify::success("Cambio de estado exitoso");
        return back();
    }

    public function activar(Request $request)
    {
        DB::table('programaciones')->where('idprogramacion',$request->idprogramacion)->update(['estado' => 1]);
        Notify::success("Cambio de estado exitoso");
        return back();
    }
}

resources/views/programacion/horario.blade.php
@extends('layout.index')

@section('top')

<div class="content-header">
  <div class="d-flex align-items-center">
    <div class="mr-auto">
      <h3 class="page-title">Inicio</h3>
      <div class="d-inline-block align-items-center">
        <nav>
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#"><i class="mdi mdi-home-outline"></i></a></li>
            <li class="breadcrumb-item active" aria-current="page">programación</li>
          </ol>
        </nav>
      </div>
    </div>
    <div class="right-title">
        <button type="button" class="btn btn-success" data-toggle="modal" data-toggle="tooltip" title="Registrar Progranación" data-target="#modal-center">
			Registrar programación
    </button>

    </div>
  </div>
</div>

@endsection

@section('contenido')

<div class="col-12">
    <div class="box box-default">
    <div class="box-header with-border">
      <h4 class="box-title">Programación</h4>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item"> <a class="nav-link active" data-toggle="tab" href="#home8" role="tab"><span><i class="ion-home mr-15"></i>Activas</span></a> </li>
        <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#profile8" role="tab"><span><i class="ion-person mr-15"></i>Inactivas</span></a> </li>
      </ul>
      <!-- Tab panes -->
      <div class="tab-content tabcontent-border">
        <div class="tab-pane active" id="home8" role="tabpanel">
          <div class="p-15">

              <div class="box-body">
                  <div class="table-responsive">
                    <table id="example5" class="table table-bordered table-striped" style="width:100%">
                    <thead>
                      <tr>
                       <th>Nombre</th>
                       <th>Inicio</th>
                       <th>Fin</th>
                       <th>Operación </th>
                      </tr>
                    </thead>
                    <tbody>
                     @foreach ($programacion as $cca)
                     <tr>
                       <td>{{ $cca->nombre }}</td>
                       <td>{{ $cca->inicio }}</td>
                       <td>{{ $cca->fin }}</td>
                        <td>
                         <button type="button" class="btn btn-success mb-3"
                         data-myinicio={{ $cca->inicio }}
                         data-myfin={{ $cca->fin }}
                         data-mynombre={{ $cca->nombre }}
                         data-myidprogramacion={{ $cca->idprogramacion }}
                         data-myidcontenido={{ $cca->idcontenido }}
                         data-myidpersona={{ $cca->idpersona }}
                         data-myidgrupo={{ $cca->idgrupo }}
                         data-toggle="modal" data-target="#editar" data-toggle="tooltip" title="Editar">
                         <a class="text-dark" ><i class="ti-pencil" aria-hidden="true"></i></a>
                        </button>
                         <form style="display: inline" method="POST" id="int" action="{{ route('programacion.destroy',$cca->idprogramacion)}}">
                             {!! csrf_field() !!}
                             {!! method_field('DELETE') !!}
                             <input type="hidden" name="idprogramacion" value="{{ $cca->idprogramacion }}">

                           <button type="button" class="btn btn-warning mb-3 sweetalert" data-toggle="tooltip" data-original-title="Inhabilitar"><a class="text-dark"><i class="ti-lock" aria-hidden="true"></i></a>
                        </form>
                       </td>
                     </tr>
                     @endforeach
                    </tbody>
                    <tfoot>
                      <tr>
                        <th>Nombre</th>
                        <th>Inicio</th>
                        <th>Fin</th>
                        <th style="display: none;"></th>
                      </tr>
                    </tfoot>
                  </table>
                  </div>
                </div>

          </div>
        </div>
        <div class="tab-pane" id="profile8" role="tabpanel">
          <div class="p-15">


              <div class="box-body">
                  <div class="table-responsive">
                    <table id="" class="table table-bordered table-striped" style="width:100%">
                    <thead>
                      <tr>
                       <th>Nombre</th>
                       <th>Inicio</th>
                       <th>Fin</th>
                       <th>Operación </th>
                      </tr>
                    </thead>
                    <tbody>
                     @foreach ($estado as $cca)
                     <tr>
                       <td>{{ $cca->nombre }}</td>
                       <td>{{ $cca->inicio }}</td>
                       <td>{{ $cca->fin }}</td>
                        <td>
                         <button type="button" class="btn btn-success mb-3"
                         data-myinicio={{ $cca->inicio }}
                         data-myfin={{ $cca->fin }}
                         data-mynombre={{ $cca->nombre }}
                         data-myidprogramacion={{ $cca->idprogramacion }}
                         data-myidcontenido={{ $cca->idcontenido }}
                         data-myidpersona={{ $cca->idpersona }}
                         data-myidgrupo={{ $cca->idgrupo }}
                         data-toggle="modal" data-target="#editar" data-toggle="tooltip" title="Editar">
                         <a class="text-dark" ><i class="ti-pencil" aria-hidden="true"></i></a>
                        </button>
                         <form style="display: inline" method="POST" action="{{ route('programacion.activar',$cca->idprogramacion)}}">
                             {!! csrf_field() !!}
                             <input type="hidden" name="idprogramacion" value="{{ $cca->idprogramacion }}">

                           <button type="submit" class="btn btn-info mb-3" data-toggle="tooltip" data-original-title="Activar"><a class="text-dark"><i class="ti-unlock" aria-hidden="true"></i></a>
                        </form>
                       </td>
                     </tr>
                     @endforeach
                    </tbody>
                    <tfoot>
                      <tr>
                        <th>Nombre</th>
                        <th>Inicio</th>
                        <th>Fin</th>
                        <th style="display: none;"></th>
                      </tr>
                    </tfoot>
                  </table>
                  </div>
                </div>

          </div>
        </div>
      </div>
    </div>
    <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>

@include('programacion.programacionmodal')

@endsection

@section('script')

<script>
    $('#editar').on('show.bs.modal', function (event) {

    var button = $(event.relatedTarget)
    var inicio = button.data('myinicio')
    var fin = button.data('myfin')
    var nombre = button.data('mynombre')
    var persona = button.data('myidpersona')
    var contenido = button.data('myidcontenido')
    var grupo = button.data('myidgrupo')
    var programacion_id = button.data('myidprogramacion')


    var modal = $(this)
    modal.find('.modal-body #nombre').val(nombre)
    modal.find('.modal-body #fin').val(fin)
    modal.find('.modal-body #inicio').val(inicio)
    modal.find('.modal-body #contenido').val(contenido)
    modal.find('.modal-body #persona').val(persona)
    modal.find('.modal-body #grupo').val(grupo)
    modal.find('.modal-body #programacion').val(programacion_id)


  });
  </script>

  @if($errors->any())
  <script>
  $('#modal-center').modal('show');
  </script>
  @endif

  @if($errors->any())
  <script>
  $('#').modal('show');
  </script>
  @endif
@endsection

resources/views/programacion/programacionmodal.blade.php
<!--Modal Actualizar-->
<div data-backdrop="static" data-keyboard="false" class="modal fade" id="editar" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="box-title text-info" id="exampleModalCenterTitle"><i class="ti-user mr-15"></i>Actualizar información </h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <form class="form" id="editarprogramacion" action="{{ route('programacion.update','text') }}" method="POST">
              {{ method_field('patch') }}
              {{ csrf_field() }}
            <div class="box-body">
                <div class="row">
                    <div class="col-md-12">
                    <div class="form-group">
                      <input type="hidden" name="idprogramacion" id="programacion" value="">
                      <label>Nombre <span class="text-danger">*</span></label>
                      <input name="nombre" id="nombre" type="text" class="form-control" placeholder=" Nombre">
                      {!!$errors->first('nombre','<span class=error>:message</span>')!!}
                    </div>
                  </div>
                </div>
              <div class="row">
                <div class="col-md-6">
                <div class="form-group">
                  <label>Inicio de horario <span class="text-danger">*</span></label>
                  <input name="inicio" id="inicio" type="date" class="form-control" placeholder="Inicio de horario">
                  {!!$errors->first('inicio','<span class=error>:message</span>')!!}
                </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                      <label>Fin de horario</label>
                      <input name="fin" id="fin" type="date" class="form-control" placeholder="Fin de horario">
                      {!!$errors->first('fin','<span class=error>:message</span>')!!}
                    </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                <div class="form-group">
                  <label>Contenido <span class="text-danger">*</span></label>
                  <select class="form-control" name="idcontenido" id="contenido" value="{{ old('idcontenido') }}">
                    @foreach ($contenido as $cca)
                    <option value="{{ $cca->idcontenido }}">{{ $cca->titulo }}</option>
                    @endforeach
                  </select>
                  {!!$errors->first('idcontenido','<span class=error>:message</span>')!!}
                </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Docente <span class="text-danger">*</span></label>
                    <select class="form-control" name="idpersona" id="persona" value="{{ old('idpersona') }}">
                      @foreach ($persona as $cca)
                      <option value="{{ $cca->idpersona }}">{{ $cca->nombre }}</option>
                      @endforeach
                    </select>
                    {!!$errors->first('idpersona','<span class=error>:message</span>')!!}
                  </div>
                  </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                <div class="form-group">
                  <label>Programación <span class="text-danger">*</span></label>
                  <select class="form-control" name="idgrupo" id="grupo" value="{{ old('idgrupo') }}">
                    @foreach ($grupo as $cca)
                    <option value="{{ $cca->idgrupo }}">{{ $cca->nombregrupo }}</option>
                    @endforeach
                  </select>
                  {!!$errors->first('idgrupo','<span class=error>:message</span>')!!}
                </div>
                </div>
              </div>
            </div>
            <!-- /.box-body -->
            <div class="modal-footer modal-footer-uniform">
                <button type="button" class="btn btn-danger btn-outline" data-dismiss="modal"><i class="ti-trash"></i> Cancelar</button>
                <button type="submit" class="btn btn-primary btn-outline float-right"><i class="ti-save-alt"></i> Actualizar</button>
            </div> 
          </form>
          <!-- /.box -->
      </div>
    </div>
  </div>
</div>


<!--Agregar-->
<div data-backdrop="static" data-keyboard="false" class="modal center-modal fade" id="modal-center" tabindex="-1">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="box-title text-info"><i class="ti-user mr-15"></i> Informacion de programación</h4>
              <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
                <div class="box">
                <!-- /.box-header -->
                
                <form class="form" id="programacion" action="{{ route('programacion.store') }}" method="POST">
                    {{ csrf_field() }}
                  <div class="box-body">
                    <div class="row">
                      <div class="col-md-12">
                      <div class="form-group">
                        <label>Nombre <span class="text-danger">*</span></label>
                        <input name="nombre" id="" type="text" class="form-control" placeholder="Programacion">
                        {!!$errors->first('nombre','<span class=error>:message</span>')!!}
                      </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group">
                          <label>Inicio de horario <span class="text-danger">*</span></label>
                          <input name="inicio" id="" type="date" class="form-control" placeholder="Inicio de horario">
                          {!!$errors->first('inicio','<span class=error>:message</span>')!!}
                        </div>
                        </div>
                        <div class="col-md-6">
                          <div class="form-group">
                            <label>Fin de horario <span class="text-danger">*</span></label>
                            <input name="fin" id="" type="date" class="form-control" placeholder="Inicio de horario">
                            {!!$errors->first('fin','<span class=error>:message</span>')!!}
                          </div>
                          </div>
                      </div>
                      <div class="row">
                        <div class="col-md-6">
                        <div class="form-group">
                          <label>Contenido <span class="text-danger">*</span></label>
                          <select class="form-control" name="idcontenido" id="" value="{{ old('idcontenido') }}">
                            @foreach ($contenido as $cca)
                            <option value="{{ $cca->idcontenido }}">{{ $cca->titulo }}</option>
                            @endforeach
                          </select>
                          {!!$errors->first('idcontenido','<span class=error>:message</span>')!!}
                        </div>
                        </div>
                        <div class="col-md-6">
                          <div class="form-group">
                            <label>Docente <span class="text-danger">*</span></label>
                            <select class="form-control" name="idpersona" id="" value="{{ old('idpersona') }}">
                              @foreach ($persona as $cca)
                              <option value="{{ $cca->idpersona }}">{{ $cca->nombre }}</option>
                              @endforeach
                            </select>
                            {!!$errors->first('idpersona','<span class=error>:message</span>')!!}
                          </div>
                          </div>
                      </div>
                      <div class="row">
                        <div class="col-md-6">
                        <div class="form-group">
                          <label>Grupo <span class="text-danger">*</span></label>
                          <select class="form-control" name="idgrupo" id="" value="{{ old('idgrupo') }}">
                            @foreach ($grupo as $cca)
                            <option value="{{ $cca->idgrupo }}">{{ $cca->nombregrupo }}</option>
                            @endforeach
                          </select>
                          {!!$errors->first('idgrupo','<span class=error>:message</span>')!!}
                        </div>
                        </div>
                      </div>
                  </div>
                  <!-- /.box-body -->
                  <div class="modal-footer modal-footer-uniform">
                      <button type="button" class="btn btn-danger btn-outline" data-dismiss="modal"><i class="ti-trash"></i> Cancelar</button>
                      <button type="submit" class="btn btn-primary btn-outline float-right"><i class="ti-save-alt"></i> Guardar</button>
                  </div> 
                </form>
                <!-- /.box -->			
          </div>
        </div>
      </div>