routes/web.php
<?php

/*Route::get('text',function(){
$user = new App\User;
$user->name = 'david';
$user->email = 'david@gmail.com';
$user->rol = 'docente';
$user->password = bcrypt('12345678');
$user->save();

return $user;
});*/

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*Controller personalizazados */
Route::get('/',['as' => '/', 'uses' => 'HomeController@index'])->middleware('auth');


Route::resource('persona', 'PersonaController');

Route::resource('matricula', 'MatriculaController');

Route::resource('users', 'UserController');

Route::resource('aula', 'AulaController');

Route::resource('grupo', 'GrupoController');

Route::resource('programacion','ProgramacionController');

Route::resource('contenido','ContenidoController');

Route::resource('perfil', 'PerfilController');

Route::get('pdf/reporte', 'pdfcontroller@reportepdf')->name('reporte.pdf');
Route::get('pdf/reportemes', 'pdfcontroller@reportemesanterior')->name('reportemes.pdf');
Route::get('pdf/reporteactual', 'pdfcontroller@reportemesactual')->name('reporteactual.pdf');
Route::get('view/reporte', 'pdfcontroller@viewpdf')->name('vista.pdf');
Route::get('view/acercade', 'pdfcontroller@acercade')->name('vista.acercade');
Route::get('view/mapa', 'pdfcontroller@mapanavegacion')->name('vista.mapanav');
Route::get('view/ayuda', 'pdfcontroller@ayuda')->name('vista.ayuda');




Route::post('persona/activar', 'PersonaController@activar')->name('persona.activar');
Route::post('users/activar', 'UserController@activar')->name('users.activar');
Route::post('aula/activar', 'AulaController@activar')->name('aula.activar');
Route::post('grupo/activar', 'GrupoController@activar')->name('grupo.activar');
Route::post('matricula/activar', 'MatriculaController@activar')->name('matricula.activar');
Route::post('programacion/activar', 'ProgramacionController@activar')->name('programacion.activar');
Route::post('contenido/activar', 'ContenidoController@activar')->name('contenido.activar');


/*End personalizazados */

/*Login y passwor reset */

Route::get('login', 'Auth\LoginController@showLoginForm');

Route::post('login', 'Auth\LoginController@login');

Route::get('logout', 'Auth\LoginController@logout');

Route::get('password/reset','Auth\ForgotPasswordController@showLinkRequestForm');

Route::post('password/email','Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');

Route::get('password/reset/{token}','ResetPasswordController@showResetForm')->name('password.reset');

Route::post('/password/reset','ResetPasswordController@reset')->name('password.send');

Auth::routes();
/*Fin login y Pssword reset */

Route::resource('home','HomeController');

app/Http/Controllers/AulaController.php
<?php

namespace App\Http\Controllers;

use DB;
use Illuminate\Http\Request;
use App\Http\Requests\RequestAula;
use App\Model\Aula;
use Notify;

class AulaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $aula = Aula::all()->where('estado','=','1');
        $aulaestado = Aula::all()->where('estado','=','0');
        return view('aula.aula',compact('aula','aulaestado'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RequestAula $request)
    {
        $input = $request->all();
        Aula::create($input);
        Notify::success("Registro exitoso");
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $aula = Aula::findOrFail($request->idaula)->update($request->all());
        Notify::success("actualizados","Datos");
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        DB::table('aulas')->where('idaula',$request->idaula)->update(['estado' => 0]);
        Notify::success("Cambio de estado exitoso");
        return redirect()->back();
    }

    public function activar(Request $request)
    {
        DB::table('aulas')->where('idaula',$request->idaula)->update(['estado' => 1]);
        Notify::success("Cambio de estado exitoso");
        return back();
    }
}

resources/views/aula/aula.blade.php
@extends('layout.index')

@section('top')

<div class="content-header">
  <div class="d-flex align-items-center">
    <div class="mr-auto">
      <h3 class="page-title">Inicio</h3>
      <div class="d-inline-block align-items-center">
        <nav>
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#"><i class="mdi mdi-home-outline"></i></a></li>
            <li class="breadcrumb-item active" aria-current="page">Aula</li>
          </ol>
        </nav>
      </div>
    </div>
    <div class="right-title">
        <button type="button" class="btn btn-success" data-toggle="tooltip" title="Registrar Aula" data-toggle="modal"  data-target="#modal-center"><a class="text-dark"><i class="ti-save" aria-hidden="true"></i></a>
			Registrar Aula
    </button>


    </div>
  </div>
</div>

@endsection

@section('contenido')

<div class="col-12">
    <div class="box box-default">
    <div class="box-header with-border">
      <h4 class="box-title">Aulas</h4>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item"> <a class="nav-link active" data-toggle="tab" href="#home8" role="tab"><span><i class="ion-home mr-15"></i>Activas</span></a> </li>
        <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#profile8" role="tab"><span><i class="ion-person mr-15"></i>Inactivas</span></a> </li>
      </ul>
      <!-- Tab panes -->
      <div class="tab-content tabcontent-border">
        <div class="tab-pane active" id="home8" role="tabpanel">
          <div class="p-15">

              <div class="box-body">
                  <div class="table-responsive">
                    <table id="example5" class="table table-bordered table-striped" style="width:100%">
                    <thead>
                      <tr>
                       <th>ID</th>
                       <th>Nombre</th>
                       <th>Operación </th>
                      </tr>
                    </thead>
                    <tbody>
                     @foreach ($aula as $cca)
                     <tr>
                       <td>{{ $cca->idaula }}</td>
                       <td>{{ $cca->nombre }}</td>
                        <td>
                         <button type="button" class="btn btn-success mb-3"
                         data-mynombre={{ $cca->nombre }}
                         data-myidaula={{ $cca->idaula }}
                         data-toggle="modal" data-target="#editar" data-toggle="tooltip" title="Editar">
                         <a class="text-dark" ><i class="ti-pencil" aria-hidden="true"></i></a>
                         </button>
                         <form style="display: inline" method="POST" id="int" action="{{ route('aula.destroy',$cca->idaula)}}">
                             {!! csrf_field() !!}
                             {!! method_field('DELETE') !!}
                             <input type="hidden" name="idaula" value="{{ $cca->idaula }}">

                             <button type="button" class="btn btn-warning mb-3 sweetalert" data-toggle="tooltip" data-original-title="Inhabilitar"><a class="text-dark"><i class="ti-lock" aria-hidden="true"></i></a>
                             </form>
                       </td>
                     </tr>
                     @endforeach
                    </tbody>
                    <tfoot>
                      <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th style="display: none;"></th>
                      </tr>
                    </tfoot>
                  </table>
                  </div>
                </div>

          </div>
        </div>
        <div class="tab-pane" id="profile8" role="tabpanel">
          <div class="p-15">


              <div class="box-body">
                  <div class="table-responsive">
                    <table id="" class="table table-bordered table-striped" style="width:100%">
                    <thead>
                      <tr>
                       <th>ID</th>
                       <th>Nombre</th>
                       <th>Operación </th>
                      </tr>
                    </thead>
                    <tbody>
                     @foreach ($aulaestado as $cca)
                     <tr>
                       <td>{{ $cca->idaula }}</td>
                       <td>{{ $cca->nombre }}</td>
                        <td>
                         <button type="button" class="btn btn-success mb-3"
                         data-mynombre={{ $cca->nombre }}
                         data-myidaula={{ $cca->idaula }}
                         data-toggle="modal" data-target="#editar" data-toggle="tooltip" title="Editar">
                         <a class="text-dark" ><i class="ti-pencil" aria-hidden="true"></i></a>
                         </button>
                         <form style="display: inline" method="POST" action="{{ route('aula.activar',$cca->idaula)}}">
                             {!! csrf_field() !!}
                             <input type="hidden" name="idaula" value="{{ $cca->idaula }}">

                             <button type="submit" class="btn btn-info mb-3" data-toggle="tooltip" data-original-title="Activar"><a class="text-dark"><i class="ti-unlock" aria-hidden="true"></i></a>
                             </form>
                       </td>
                     </tr>
                     @endforeach
                    </tbody>
                    <tfoot>
                      <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th style="display: none;"></th>
                      </tr>
                    </tfoot>
                  </table>
                  </div>
                </div>

          </div>
        </div>
      </div>
    </div>
    <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>


<div class="col-12">

  <div class="box">
   <div class="box-header with-border">
     <h3 class="box-title"> Aula</h3>
   </div>
   <!-- /.box-header -->

   <!-- /.box-body -->
   </div>
   <!-- /.box -->
 </div>

  @include('aula.modalaula')

@endsection

@section('script')

<script>
    $('#editar').on('show.bs.modal', function (event) {

    var button = $(event.relatedTarget)
    var name = button.data('mynombre')
    var aula_id = button.data('myidaula')

    var modal = $(this)
    modal.find('.modal-body #nombre').val(name)
    modal.find('.modal-body #aula').val(aula_id)

  });
  </script>

  @if($errors->any())
  <script>
  $('#modal-center').modal('show');
  </script>
  @endif

@endsection

resources/views/aula/modalaula.blade.php
<!--Modal Actualizar-->
<div data-backdrop="static" data-keyboard="false" class="modal fade" id="editar" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="box-title text-info" id="exampleModalCenterTitle"><i class="ti-user mr-15"></i>Actualizar Informacion</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <form class="form" id="editaraula" action="{{ route('aula.update','text') }}" method="POST">
              {{ method_field('patch') }}
              {{ csrf_field() }}
            <div class="box-body">
              <div class="row">
                <div class="col-md-12">
                <div class="form-group">
                  <input type="hidden" name="idaula" id="aula" value="">
                  <label>Primer nombre <span class="text-danger">*</span></label>
                  <input name="nombre" id="nombre" type="text" class="form-control" placeholder="Nombre Aula">
                  {!!$errors->first('nombre','<span class=error>:message</span>')!!}
                </div>
                </div>
              </div>
            </div>
            <!-- /.box-body -->
            <div class="modal-footer modal-footer-uniform">
                <button type="button" class="btn btn-danger btn-outline" data-dismiss="modal"><i class="ti-trash"></i> Cancelar</button>
                <button type="submit" class="btn btn-primary btn-outline float-right"><i class="ti-save-alt"></i> Actualizar</button>
            </div> 
          </form>
          <!-- /.box -->
      </div>
    </div>
  </div>
</div>


<!--Agregar-->
<div data-backdrop="static" data-keyboard="false" class="modal center-modal fade" id="modal-center" tabindex="-1">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="box-title text-info"><i class="ti-user mr-15"></i> Informacion Aula</h4>
              <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
                <div class="box">
                <!-- /.box-header -->
                
                <form class="form" id="modalaula" action="{{ route('aula.store') }}" method="POST">
                    {{ csrf_field() }}
                  <div class="box-body">
                    <div class="row">
                      <div class="col-md-12">
                      <div class="form-group">
                        <label>Nombre aula <span class="text-danger">*</span></label>
                        <input name="nombre" id="" type="text" class="form-control" placeholder="Nombre Aula">
                        {!!$errors->first('nombre','<span class=error>:message</span>')!!}
                      </div>
                      </div>
                    </div>
                  </div>
                  <!-- /.box-body -->
                  <div class="modal-footer modal-footer-uniform">
                      <button type="button" class="btn btn-danger btn-outline" data-dismiss="modal"><i class="ti-trash"></i> Cancelar</button>
                      <button type="submit" class="btn btn-primary btn-outline float-right"><i class="ti-save-alt"></i> Guardar</button>
                  </div> 
                </form>
                <!-- /.box -->			
          </div>
        </div>
      </div>