routes/web.php
<?php

/*Route::get('text',function(){
$user = new App\User;
$user->name = 'david';
$user->email = 'david@gmail.com';
$user->rol = 'docente';
$user->password = bcrypt('12345678');
$user->save();

return $user;
});*/

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*Controller personalizazados */
Route::get('/',['as' => '/', 'uses' => 'HomeController@index'])->middleware('auth');


Route::resource('persona', 'PersonaController');

Route::resource('matricula', 'MatriculaController');

Route::resource('users', 'UserController');

Route::resource('aula', 'AulaController');

Route::resource('grupo', 'GrupoController');

Route::resource('programacion','ProgramacionController');

Route::resource('contenido','ContenidoController');

Route::resource('perfil', 'PerfilController');

Route::get('pdf/reporte', 'pdfcontroller@reportepdf')->name('reporte.pdf');
Route::get('pdf/reportemes', 'pdfcontroller@reportemesanterior')->name('reportemes.pdf');
Route::get('pdf/reporteactual', 'pdfcontroller@reportemesactual')->name('reporteactual.pdf');
Route::get('view/reporte', 'pdfcontroller@viewpdf')->name('vista.pdf');
Route::get('view/acercade', 'pdfcontroller@acercade')->name('vista.acercade');
Route::get('view/mapa', 'pdfcontroller@mapanavegacion')->name('vista.mapanav');
Route::get('view/ayuda', 'pdfcontroller@ayuda')->name('vista.ayuda');




Route::post('persona/activar', 'PersonaController@activar')->name('persona.activar');
Route::post('users/activar', 'UserController@activar')->name('users.activar');
Route::post('aula/activar', 'AulaController@activar')->name('aula.activar');
Route::post('grupo/activar', 'GrupoController@activar')->name('grupo.activar');
Route::post('matricula/activar', 'MatriculaController@activar')->name('matricula.activar');
Route::post('programacion/activar', 'ProgramacionController@activar')->name('programacion.activar');
Route::post('contenido/activar', 'ContenidoController@activar')->name('contenido.activar');


/*End personalizazados */

/*Login y passwor reset */

Route::get('login', 'Auth\LoginController@showLoginForm');

Route::post('login', 'Auth\LoginController@login');

Route::get('logout', 'Auth\LoginController@logout');

Route::get('password/reset','Auth\ForgotPasswordController@showLinkRequestForm');

Route::post('password/email','Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');

Route::get('password/reset/{token}','ResetPasswordController@showResetForm')->name('password.reset');

Route::post('/password/reset','ResetPasswordController@reset')->name('password.send');

Auth::routes();
/*Fin login y Pssword reset */

Route::resource('home','HomeController');

app/Http/Controllers/GrupoController.php
<?php

namespace App\Http\Controllers;

use DB;
use Illuminate\Http\Request;
use App\Http\Requests\RequestGrupo;
use App\Model\Grupo;
use App\Model\Aula;
use App\Model\Programacione;
use Notify;

class GrupoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   // $grupo = Grupo::all();

        $grupo = DB::table('grupos')
        ->join('aulas', 'aulas.idaula', '=', 'grupos.aula_idaula')
        ->select('aulas.*', 'grupos.nombregrupo', 'grupos.cantidad','grupos.aula_idaula','grupos.idgrupo',
        'grupos.horario')->where('grupos.estado','=','1')
        ->get();

        $estadogrupo = DB::table('grupos')
        ->join('aulas', 'aulas.idaula', '=', 'grupos.aula_idaula')
        ->select('aulas.*', 'grupos.nombregrupo', 'grupos.cantidad','grupos.aula_idaula','grupos.idgrupo',
        'grupos.horario')->where('grupos.estado','=','0')
        ->get();

        $aula = Aula::all()->where('estado','=','1');
        $programacion = Programacione::all();
        return view('grupo.grupo',compact('grupo','aula','estadogrupo','programacion'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RequestGrupo $request)
    {
        $estado = DB::table('aulas')->select('estado')->where('idaula',$request->aula_idaula)->get();
        

        if($estado=1){
        $input = $request->all();
        Grupo::create($input);
        Notify::success("Registro exitoso");
        $aula = DB::table('aulas')->where('idaula',$request->aula_idaula)->update(['estado' => 0]);
        return redirect()->back();
       }else{
        Notify::error("esta en uso","El aula");
        return redirect()->back();
       }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $personas = DB::table('personas')->select('*') ->where([ ['Id_tipopersona','=','2'], ['estado','=','1'],])->get();
        
        $grupos = Grupo::all();

        $gruposhow = Grupo::all()->where('idgrupo',$id)->first();

        $programacion = DB::table('programaciones')
        ->join('contenidos','contenidos.idcontenido', '=', 'programaciones.idcontenido')
        ->select('programaciones.*','contenidos.*')->where('programaciones.idgrupo',$id)->get();

        $matriculagrupos = DB::table('matriculas')
        ->join('personas', 'personas.idpersona', '=', 'matriculas.idpersona')
        ->select('matriculas.*', 'personas.nombre', 'personas.cedula','personas.direccion','personas.telefono',
        'personas.fecha_nacimiento','personas.apellido','personas.snombre')->where([ ['idgrupo','=',$id], ['matriculas.estado','=','1'],])
        ->get();

        $estadoM = DB::table('matriculas')
        ->join('personas', 'personas.idpersona', '=', 'matriculas.idpersona')
        ->select('matriculas.*', 'personas.nombre', 'personas.cedula','personas.direccion','personas.telefono',
        'personas.fecha_nacimiento','personas.apellido','personas.snombre')->where([ ['idgrupo','=',$id], ['matriculas.estado','=','0'],])
        ->get();


        return view('grupo.consultaGrupo',compact('gruposhow','matriculagrupos','grupos','personas','estadoM','programacion'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $grupo = Grupo::findOrFail($request->idgrupo)->update($request->all());
        Notify::success("actualizados","Datos");
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $aula = DB::table('grupos')->where('idgrupo',$request->idgrupo)->update(['estado' => 0]);
        Notify::success("Cambio de estado exitoso");
        return back();
    }

    public function activar(Request $request)
    {
        $aula = DB::table('grupos')->where('idgrupo',$request->idgrupo)->update(['estado' => 1]);
        Notify::success("Cambio de estado exitoso");
        return back();
    }
}

resources/views/grupo/consultaGrupo.blade.php
@extends('layout.index')

@section('top')

<div class="content-header">
  <div class="d-flex align-items-center">
    <div class="mr-auto">
      <h3 class="page-title">Inicio</h3>
      <div class="d-inline-block align-items-center">
        <nav>
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#"><i class="mdi mdi-home-outline"></i></a></li>
            <li class="breadcrumb-item active" aria-current="page">Grupo</li>
          </ol>
        </nav>
      </div>
    </div>
    <div class="right-title">
        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#modal-center">
			Registar Matricula
        </button> 
        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModalCenter">
         Programacion del grupo
         </button>
    </div>
  </div>
</div>

@endsection

@section('contenido')

<div class="col-12">
    <div class="box box-default">
    <div class="box-header with-border">
      <h4 class="box-title">Matriculados en este grupo</h4>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item"> <a class="nav-link active" data-toggle="tab" href="#home8" role="tab"><span><i class="ion-home mr-15"></i>Activo</span></a> </li>
        <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#profile8" role="tab"><span><i class="ion-person mr-15"></i>Inactivos</span></a> </li>
      </ul>
      <!-- Tab panes -->
      <div class="tab-content tabcontent-border">
        <div class="tab-pane active" id="home8" role="tabpanel">
          <div class="p-15">

              <div class="box-body">
                  <div class="table-responsive">
                    <table id="example5" class="table table-bordered table-striped" style="width:100%">
                    <thead>
                      <tr>
                       <th>Nombre</th>
                       <th>Cedula</th>
                       <th>Direccion</th>
                       <th>Telefono</th>
                       <th>Fechade nacimiento</th>
                       <th>Pago</th>
                       <th class="tamaño">Operación </th>
                      </tr>
                    </thead>
                    <tbody>
                         @foreach ($matriculagrupos as $cca)
                         <tr>
                           <td>{{ $cca->nombre }}&nbsp;{{ $cca->apellido }}</td>
                           <td>{{ $cca->cedula }}</td>
                           <td>{{ $cca->direccion }}</td>
                           <td>{{ $cca->telefono }}</td>
                           <td>{{ $cca->fecha_nacimiento }}</td>
                           <td>{{ $cca->pago }}</td>
                           <td>
                           <button type="button" class="btn btn-success mb-3"
                               data-mypago={{ $cca->pago }}
                               data-myidgrupo={{ $cca->idgrupo }}
                               data-myidmatricula={{ $cca->idmatriculas }}
                               data-toggle="modal" data-target="#editar" data-toggle="tooltip" title="Editar">
                               <a class="text-dark" ><i class="ti-pencil" aria-hidden="true"></i></a>
                           </button> 
                           <form style="display: inline" method="POST" action="{{ route('matricula.destroy',$cca->idmatriculas)}}">
                             {!! csrf_field() !!}
                             {!! method_field('DELETE') !!}
                             <input type="hidden" name="idmatricula" value="{{ $cca->idmatriculas }}">
                 
                             <button type="submit" class="btn btn-warning mb-3" data-toggle="tooltip" data-original-title="Dasactivar"><i ><a class="text-dark"><i class="ti-lock" aria-hidden="true"></i></a></i> </button>
                          </form>
                         </td>
                         </tr>
                         @endforeach
                    </tbody>
                    <tfoot>
                      <tr>
                      <th></th>
                      <th></th>
                      <th></th>
                      <th></th>
                      <th></th>
                      <th></th>
                      <th id="oculta"></th>
                      </tr>
                    </tfoot>
                  </table>
                  </div>
                </div>


          </div>
        </div>
        <div class="tab-pane" id="profile8" role="tabpanel">
          <div class="p-15">

              <div class="box-body">
                  <div class="table-responsive">
                    <table id="" class="table table-bordered table-striped" style="width:100%">
                    <thead>
                      <tr>
                       <th>Nombre</th>
                       <th>Cedula</th>
                       <th>Direccion</th>
                       <th>Telefono</th>
                       <th>Fechade nacimiento</th>
                       <th>Pago</th>
                       <th class="tamaño">Operación </th>
                      </tr>
                    </thead>
                    <tbody>
                         @foreach ($estadoM as $cca)
                         <tr>
                           <td>{{ $cca->nombre }}&nbsp;{{ $cca->apellido }}</td>
                           <td>{{ $cca->cedula }}</td>
                           <td>{{ $cca->direccion }}</td>
                           <td>{{ $cca->telefono }}</td>
                           <td>{{ $cca->fecha_nacimiento }}</td>
                           <td>{{ $cca->pago }}</td>
                           <td>
                           <button type="button" class="btn btn-success mb-3"
                               data-mypago={{ $cca->pago }}
                               data-myidgrupo={{ $cca->idgrupo }}
                               data-myidmatricula={{ $cca->idmatriculas }}
                               data-toggle="modal" data-target="#editar" data-toggle="tooltip" title="Editar">
                               <a class="text-dark" ><i class="ti-pencil" aria-hidden="true"></i></a>
                           </button> 
                           <form style="display: inline" method="POST" action="{{ route('matricula.activar',$cca->idmatriculas)}}">
                             {!! csrf_field() !!}
                             <input type="hidden" name="idmatricula" value="{{ $cca->idmatriculas }}">
                 
                             <button type="submit" class="btn btn-warning mb-3" data-toggle="tooltip" data-original-title="Activar"><i ><a class="text-dark"><i class="ti-lock" aria-hidden="true"></i></a></i> </button>
                          </form>
                         </td>
                         </tr>
                         @endforeach
                    </tbody>
                    <tfoot>
                      <tr>
                      <th></th>
                      <th></th>
                      <th></th>
                      <th></th>
                      <th></th>
                      <th></th>
                      <th id="oculta"></th>
                      </tr>
                    </tfoot>
                  </table>
                  </div>
                </div>

          </div>
        </div>
      </div>
    </div>
    <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>

 @include('grupo.detallesdeprogramacion')
 @include('matricula.modalmatricula')
@endsection

@section('script')

<script>
    $('#editar').on('show.bs.modal', function (event) {
  
    var button = $(event.relatedTarget) 
    var pago = button.data('mypago')
    var idgrupo = button.data('myidgrupo')
    var matricula_id = button.data('myidmatricula')
       
  
    var modal = $(this)
    modal.find('.modal-body #pago').val(pago)
    modal.find('.modal-body #idgrupo').val(idgrupo)
    modal.find('.modal-body #matricula').val(matricula_id)
    
  });
  </script>

  @if($errors->any())
  <script>
  $('#modal-center').modal('show');
  </script>
  @endif
@endsection

resources/views/grupo/grupo.blade.php
@extends('layout.index')

@section('top')

<div class="content-header">
  <div class="d-flex align-items-center">
    <div class="mr-auto">
      <h3 class="page-title">Inicio</h3>
      <div class="d-inline-block align-items-center">
        <nav>
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#"><i class="mdi mdi-home-outline"></i></a></li>
            <li class="breadcrumb-item active" aria-current="page">Grupo</li>
          </ol>
        </nav>
      </div>
    </div>
    <div class="right-title">
        <button type="button" class="btn btn-success" data-toggle="modal" data-toggle="tooltip" title="Registrar Aula" data-target="#modal-center">
						Registrar Grupo
        </button>
    </div>
  </div>
</div>

@endsection

@section('contenido')

<div class="col-12">
    <div class="box box-default">
    <div class="box-header with-border">
      <h4 class="box-title">Grupos</h4>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item"> <a class="nav-link active" data-toggle="tab" href="#home8" role="tab"><span><i class="ion-home mr-15"></i>Activos</span></a> </li>
        <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#profile8" role="tab"><span><i class="ion-person mr-15"></i>Inactivos</span></a> </li>
      </ul>
      <!-- Tab panes -->
      <div class="tab-content tabcontent-border">
        <div class="tab-pane active" id="home8" role="tabpanel">
          <div class="p-15">

              <div class="box-body">
                  <div class="table-responsive">
                    <table id="example5" class="table table-bordered table-striped" style="width:100%">
                    <thead>
                      <tr>
                       <th>Nombre Grupo</th>
                       <th>Cantidad de estudiantes</th>
                       <th>Nombre Auala</th>
                       <th>Operación </th>
                      </tr>
                    </thead>
                    <tbody>
                     @foreach ($grupo as $cca)
                     <tr>
                       <td>{{ $cca->nombregrupo }}</td>
                       <td>{{ $cca->cantidad }}</td>
                       <td>{{ $cca->nombre }}</td>
                        <td>
                         <button type="button" class="btn btn-success mb-3"
                         data-mynombre={{ $cca->nombregrupo }}
                         data-mycantidad={{ $cca->cantidad }}
                         data-myidaula={{ $cca->aula_idaula }}
                         data-myidgrupo={{ $cca->idgrupo }}
                         data-myhorario={{ $cca->horario }}
                         data-toggle="modal" data-target="#editar" data-toggle="tooltip" title="Editar">
                         <a class="text-dark" ><i class="ti-pencil" aria-hidden="true"></i></a>
                        </button>

                         <form style="display: inline"  action="{{ route('grupo.show',$cca->idgrupo)}}">
                             <button type="submit" class="btn btn-info mb-3" data-toggle="tooltip" data-original-title="Detalles"><a class="text-dark"><i class="ti-eye" aria-hidden="true"></i></a>
                         </form>

                         <form style="display: inline" method="POST" id="int" action="{{ route('grupo.destroy',$cca->idgrupo)}}">
                             {!! csrf_field() !!}
                             {!! method_field('DELETE') !!}
                              <input type="hidden" name="idgrupo" value="{{ $cca->idgrupo }}">

                             <button type="button" class="btn btn-warning mb-3 sweetalert" data-toggle="tooltip" data-original-title="Inhabilitar"><a class="text-dark"><i class="ti-lock" aria-hidden="true"></i></a>
                          </form>
                       </td>
                     </tr>
                     @endforeach
                    </tbody>
                    <tfoot>
                      <tr>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th style="display: none;"></th>
                      </tr>
                    </tfoot>
                  </table>
                  </div>
                </div>

          </div>
        </div>
        <div class="tab-pane" id="profile8" role="tabpanel">
          <div class="p-15">

              <div class="box-body">
                  <div class="table-responsive">
                    <table id="" class="table table-bordered table-striped" style="width:100%">
                    <thead>
                      <tr>
                       <th>Nombre Grupo</th>
                       <th>Cantidad de estudiantes</th>
                       <th>Nombre Auala</th>
                       <th>Operación </th>
                      </tr>
                    </thead>
                    <tbody>
                     @foreach ($estadogrupo as $cca)
                     <tr>
                       <td>{{ $cca->nombregrupo }}</td>
                       <td>{{ $cca->cantidad }}</td>
                       <td>{{ $cca->nombre }}</td>
                        <td>
                         <button type="button" class="btn btn-success mb-3"
                         data-mynombre={{ $cca->nombregrupo }}
                         data-mycantidad={{ $cca->cantidad }}
                         data-myidaula={{ $cca->aula_idaula }}
                         data-myidgrupo={{ $cca->idgrupo }}
                         data-myhorario={{ $cca->horario }}
                         data-toggle="modal" data-target="#editar" data-toggle="tooltip" title="Editar">
                         <a class="text-dark" ><i class="ti-pencil" aria-hidden="true"></i></a>
                        </button>

                         <form style="display: inline"  action="{{ route('grupo.show',$cca->idgrupo)}}">
                             <button type="submit" class="btn btn-info mb-3" data-toggle="tooltip" data-original-title="Detalles"><a class="text-dark"><i class="ti-eye" aria-hidden="true"></i></a>
                         </form>

                         <form style="display: inline" method="POST" action="{{ route('grupo.activar',$cca->idgrupo)}}">
                             {!! csrf_field() !!}
                              <input type="hidden" name="idgrupo" value="{{ $cca->idgrupo }}">

                             <button type="submit" class="btn btn-info mb-3" data-toggle="tooltip" data-original-title="Activar"><a class="text-dark"><i class="ti-unlock" aria-hidden="true"></i></a>
                          </form>
                       </td>
                     </tr>
                     @endforeach
                    </tbody>
                    <tfoot>
                      <tr>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Cedula</th>
                        <th style="display: none;"></th>
                      </tr>
                    </tfoot>
                  </table>
                  </div>
                </div>

          </div>
        </div>
      </div>
    </div>
    <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>

@include('grupo.modalgrupo')

@endsection

@section('script')

<script>
    $('#editar').on('show.bs.modal', function (event) {

    var button = $(event.relatedTarget)
    var nombre = button.data('mynombre')
    var cantidad = button.data('mycantidad')
    var id_aula = button.data('myidaula')
    var grupo_id = button.data('myidgrupo')
    var horario = button.data('myhorario')
    var iddocente = button.data('myiddocente')



    var modal = $(this)
    modal.find('.modal-body #nombregrupo').val(nombre)
    modal.find('.modal-body #cantidad').val(cantidad)
    modal.find('.modal-body #idaula').val(id_aula)
    modal.find('.modal-body #horario').val(horario)
    modal.find('.modal-body #docentes').val(iddocente)
    modal.find('.modal-body #grupo').val(grupo_id)

  });
  </script>

  @if($errors->any())
  <script>
  $('#modal-center').modal('show');
  </script>
  @endif
@endsection

resources/views/grupo/modalgrupo.blade.php
<!--Modal Actualizar-->
<div data-backdrop="static" data-keyboard="false" class="modal fade" id="editar" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="box-title text-info" id="exampleModalCenterTitle"><i class="ti-user mr-15"></i>Actualizar información </h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form class="form" id="editargrupo" action="{{ route('grupo.update','text') }}" method="POST">
          {{ method_field('patch') }}
          {{ csrf_field() }}
        <div class="box-body">
          <div class="row">
            <div class="col-md-6">
            <div class="form-group">
              <input type="hidden" name="idgrupo" id="grupo" value="">
              <label>Nombre grupo <span class="text-danger">*</span></label>
              <input name="nombregrupo" id="nombregrupo" type="text" class="form-control" placeholder="Nombre Grupo">
              {!!$errors->first('nombregrupo','<span class=error>:message</span>')!!}
            </div>
            </div>
            <div class="col-md-6">
            <div class="form-group">
              <label>Cantidad de estudientes</label>
              <input name="cantidad" id="cantidad" type="number" class="form-control" placeholder="Cantidad De Estudientes">
              {!!$errors->first('cantidad','<span class=error>:message</span>')!!}
            </div>
            </div>
          </div>

            <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Aula <span class="text-danger">*</span></label>
                    <select class="form-control" name="aula_idaula" id="idaula">
                      @foreach ($aula as $cca)
                      <option value="{{ $cca->idaula }}">{{ $cca->nombre }}</option>
                      @endforeach
                    </select>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label> Horario</label>
                    <select class="form-control" name="horario" id="horario">
                    <option> Mañana</option>
                    <option> Tarde</option>
                    </select>
                  </div>
                </div>
              </div>
        </div>
        <!-- /.box-body -->
        <div class="modal-footer modal-footer-uniform">
            <button type="button" class="btn btn-danger btn-outline" data-dismiss="modal"><i class="ti-trash"></i> Cancelar</button>
            <button type="submit" class="btn btn-primary btn-outline float-right"><i class="ti-save-alt"></i> Actualizar</button>
        </div> 
      </form>
      </div>
    </div>
  </div>
</div>


<!--AGREGAR-->
  <div data-backdrop="static" data-keyboard="false" class="modal center-modal fade registrar" id="modal-center" tabindex="-1">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="box-title text-info"><i class="ti-user mr-15"></i> Informacion</h4>
              <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
                <div class="box">
                <!-- /.box-header -->
                
                <form class="form" id="modalgrupo" action="{{ route('grupo.store') }}" method="POST">
                    {{ csrf_field() }}
                  <div class="box-body">
                    <div class="row">
                      <div class="col-md-6">
                      <div class="form-group">
                        <label>Nombre de grupo <span class="text-danger">*</span></label>
                        <input name="nombregrupo" id="" type="text" class="form-control" placeholder="Nombre De Grupo">
                        {!!$errors->first('nombregrupo','<span class=error>:message</span>')!!}
                      </div>
                      </div>
                      <div class="col-md-6">
                      <div class="form-group">
                        <label>Cantidad de integentes</label>
                        <input name="cantidad" id="" type="number" class="form-control" placeholder="Cantidad De Integentes">
                        {!!$errors->first('cantidad','<span class=error>:message</span>')!!}
                      </div>
                      </div>
                    </div>

                      <div class="row">
                        <div class="col-md-6">
                          <div class="form-group">
                            <label>Aula <span class="text-danger">*</span></label>
                            <select class="form-control" name="aula_idaula">
                              @foreach ($aula as $cca)
                              <option value="{{ $cca->idaula }}">{{ $cca->nombre }}</option>
                              @endforeach
                            </select>
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="form-group">
                            <label> Horario</label>
                            <select class="form-control" name="horario" id="">
                            <option> Mañana</option>
                            <option> Tarde</option>
                            </select>
                          </div>
                        </div>
                      </div>
                  </div>
                  <!-- /.box-body -->
                  <div class="modal-footer modal-footer-uniform">
                      <button type="button" class="btn btn-danger btn-outline" data-dismiss="modal"><i class="ti-trash"></i> Cancelar</button>
                      <button type="submit" class="btn btn-primary btn-outline float-right"><i class="ti-save-alt"></i> Guardar</button>
                  </div> 
                </form>
                <!-- /.box -->			
          </div>
        </div>
      </div>